In [8]:
from mmnl import MMNL
import numpy as np
import pickle
import pandas as pd
import time

In [ ]:
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

Authorize Google Drive to upload files to the drive

In [ ]:
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

In [3]:
def load_data(path):
    dat = np.load(path)
    X = dat[:, :-1]
    Y = np.reshape(dat[:, -1], (-1, 1))
    return X, Y
X, Y = load_data('data/data.npy')

Load data

In [4]:
%%time
infile = open('./data/1000_Y_dgp_tim.p', 'rb')
Y_dgp = pickle.load(infile)
# Y_dgp = big_dict['theta: [ 1.5  1.  -1.1  0.4  0.1  0.6]']
print(Y_dgp.shape, '\n',Y_dgp)

(2798, 1000) 
 [[3. 3. 0. ... 0. 1. 2.]
 [3. 3. 1. ... 0. 1. 3.]
 [1. 1. 1. ... 0. 3. 1.]
 ...
 [3. 3. 3. ... 3. 3. 3.]
 [3. 3. 3. ... 3. 3. 1.]
 [2. 2. 1. ... 2. 1. 2.]]
Wall time: 55.9 ms


In [ ]:
%%time
m = [250,500,1000]
for draws in m:
    t=time.time()
    result = []
    start = 100
    end = 200
    method = 'SMC'
    for i in range(start,end):
        print('iteration: %i' %(i+1))
        qmc = MMNL(X,Y_dgp[:,i],draws,3,method=method)
        solution = qmc.solver()
        result.append(solution)
        if i%10==9:
            pickle.dump( result, open( "./resultaten/%s(%i)/%i-%i_%s(%i)_timgdp_results.p" %(method,draws,i-9,i,method,draws), "wb" ) )
            result = []
    print('%s(%i) run time: %f'%(method,draws,time.time()-t))
#     f = drive.CreateFile()
#     f.SetContentFile("./resultaten/%i-%i_%s(%i)_results.p" %(i,i+10,method,draws))
#     f.Upload()

iteration: 101
      fun: 2926.8837786001
 hess_inv: <6x6 LbfgsInvHessProduct with dtype=float64>
      jac: array([ 4.04725142e-03,  1.27329258e-03,  1.13686838e-02, -3.63797881e-04,
       -9.09494702e-05, -1.50066626e-03])
  message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
     nfev: 308
      nit: 36
   status: 0
  success: True
        x: array([ 1.55059938,  1.04004456, -1.02153969, -1.25299261, -7.83768259,
       -0.67692547]) 
 19.658084869384766
iteration: 102
      fun: 2947.983941867745
 hess_inv: <6x6 LbfgsInvHessProduct with dtype=float64>
      jac: array([-1.45519152e-03, -6.82121026e-04,  2.72848411e-04,  9.09494702e-05,
        2.72848411e-04,  1.13686838e-03])
  message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
     nfev: 231
      nit: 26
   status: 0
  success: True
        x: array([ 1.4890769 ,  1.13368369, -1.05497313, -0.62737839, -2.80231877,
       -0.4596106 ]) 
 16.703702926635742
iteration: 103
      fun: 2913.373623416356
 hess_inv: <