In [2]:
from mmnl import MMNL
import numpy as np
import pickle
import pandas as pd
import time

In [ ]:
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

Authorize Google Drive to upload files to the drive

In [ ]:
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

In [3]:
def load_data(path):
    dat = np.load(path)
    X = dat[:, :-1]
    Y = np.reshape(dat[:, -1], (-1, 1))
    return X, Y
X, Y = load_data('data/data.npy')

Load data

In [4]:
%%time
infile = open('./data/1000_Y_dgp_tim.p', 'rb')
Y_dgp = pickle.load(infile)
# Y_dgp = big_dict['theta: [ 1.5  1.  -1.1  0.4  0.1  0.6]']
print(Y_dgp.shape, '\n',Y_dgp)

(2798, 1000) 
 [[3. 3. 0. ... 0. 1. 2.]
 [3. 3. 1. ... 0. 1. 3.]
 [1. 1. 1. ... 0. 3. 1.]
 ...
 [3. 3. 3. ... 3. 3. 3.]
 [3. 3. 3. ... 3. 3. 1.]
 [2. 2. 1. ... 2. 1. 2.]]
Wall time: 63.9 ms


In [ ]:
%%time
m = [50,75]
for draws in m:
    t=time.time()
    result = []
    start = 170
    end = 200
    method = 'BQMC'
    skips = 0
    for i in range(start,end):
        print('iteration: %i' %(i+1))
        try:
            qmc = MMNL(X,Y_dgp[:,i],draws,3,method=method)
            solution = qmc.solver()
            result.append(solution)
        except np.linalg.LinAlgError:
            skips += 1
            print('deze is overgeslagen, optimizer doet naar, %i skips'%(skips))
        if len(result)== 10:
            pickle.dump( result, open( "./resultaten/%s(%i)/%i-%i_%s(%i)_timgdp_results.p" %(method,draws,i-9,i,method,draws), "wb" ) )
            result = []
            skips = 0
    print('%s(%i) run time: %f'%(method,draws,time.time()-t))
#     f = drive.CreateFile()
#     f.SetContentFile("./resultaten/%i-%i_%s(%i)_results.p" %(i,i+10,method,draws))
#     f.Upload()

iteration: 171
deze is overgeslagen, optimizer doet naar, 1 skips
iteration: 172
      fun: 3006.5721245802397
 hess_inv: <6x6 LbfgsInvHessProduct with dtype=float64>
      jac: array([   41.61393008,    63.35089893, -1586.97366714,  -189.72232283,
        -289.58802432,  1844.9988147 ])
  message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
     nfev: 203
      nit: 8
   status: 0
  success: True
        x: array([ 2.21287086,  1.4993783 , -0.90720438, -0.62158412, -1.2885142 ,
       -1.80042403]) 
 56.27368092536926
iteration: 173
deze is overgeslagen, optimizer doet naar, 2 skips
iteration: 174
deze is overgeslagen, optimizer doet naar, 3 skips
iteration: 175
deze is overgeslagen, optimizer doet naar, 4 skips
iteration: 176
deze is overgeslagen, optimizer doet naar, 5 skips
iteration: 177
      fun: 3072.339789942378
 hess_inv: <6x6 LbfgsInvHessProduct with dtype=float64>
      jac: array([119.56353774,  51.83833309, 226.2828275 , 266.85993362,
       162.90414351, -42.82264