In [1]:
from mmnl import MMNL
import numpy as np
import pickle
import pandas as pd
import time

In [ ]:
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

Authorize Google Drive to upload files to the drive

In [ ]:
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

In [2]:
def load_data(path):
    dat = np.load(path)
    X = dat[:, :-1]
    Y = np.reshape(dat[:, -1], (-1, 1))
    return X, Y
X, Y = load_data('data/data.npy')

Load data

In [3]:
%%time
infile = open('./data/1000_Y_dgp_tim.p', 'rb')
Y_dgp = pickle.load(infile)
# Y_dgp = big_dict['theta: [ 1.5  1.  -1.1  0.4  0.1  0.6]']
print(Y_dgp.shape, '\n',Y_dgp)

(2798, 1000) 
 [[3. 3. 0. ... 0. 1. 2.]
 [3. 3. 1. ... 0. 1. 3.]
 [1. 1. 1. ... 0. 3. 1.]
 ...
 [3. 3. 3. ... 3. 3. 3.]
 [3. 3. 3. ... 3. 3. 1.]
 [2. 2. 1. ... 2. 1. 2.]]
Wall time: 72.3 ms


In [ ]:
%%time
m = [50,75]
for draws in m:
    t=time.time()
    result = []
    start = 0
    end = 200
    method = 'BQMC'
    skips = 0
    for i in range(start,end):
        print('iteration: %i' %(i+1))
        try:
            qmc = MMNL(X,Y_dgp[:,i],draws,3,method=method)
            solution = qmc.solver()
            result.append(solution)
        except np.linalg.LinAlgError:
            skips += 1
            print('deze is overgeslagen, optimizer doet naar, %i skips'%(skips))
        if len(result)== 10:
            pickle.dump( result, open( "./resultaten/%s(%i)/%i-%i_%s(%i)_timgdp_results.p" %(method,draws,i-9,i,method,draws), "wb" ) )
            result = []
            skips = 0
    print('%s(%i) run time: %f'%(method,draws,time.time()-t))
#     f = drive.CreateFile()
#     f.SetContentFile("./resultaten/%i-%i_%s(%i)_results.p" %(i,i+10,method,draws))
#     f.Upload()

iteration: 1
      fun: 2967.478806910389
 hess_inv: <6x6 LbfgsInvHessProduct with dtype=float64>
      jac: array([ -20.74984877,   29.43193067,   -5.18980414, 1408.59883686,
        896.53358373, -132.41847228])
  message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
     nfev: 938
      nit: 25
   status: 0
  success: True
        x: array([ 1.37224579,  1.46327574, -1.06048092, -0.60491044, -1.22089352,
       -1.90790259]) 
 291.41967511177063
iteration: 2
      fun: 2911.469630970128
 hess_inv: <6x6 LbfgsInvHessProduct with dtype=float64>
      jac: array([  12.95261427,   31.98229024, -103.01632756,  227.48699848,
        421.74897317,  -65.01149983])
  message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
     nfev: 210
      nit: 10
   status: 0
  success: True
        x: array([ 1.63890048,  1.4202801 , -1.31054194, -0.59167169, -1.24880688,
       -1.64504086]) 
 66.73606300354004
iteration: 3
      fun: 2976.1128922202647
 hess_inv: <6x6 LbfgsInvHessProduct with

C:\Users\niels\git\Thesis\mmnl.py:283: RuntimeWarning: invalid value encountered in log
  return np.sum(np.log(mean_prod+1e-6)), cov_prod


deze is overgeslagen, optimizer doet naar, 1 skips
iteration: 16
      fun: 3075.791074920944
 hess_inv: <6x6 LbfgsInvHessProduct with dtype=float64>
      jac: array([ -34.84096851,   45.2968834 , 1044.72724161,  408.88849071,
        937.96193141,  104.37047422])
  message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
     nfev: 287
      nit: 9
   status: 0
  success: True
        x: array([ 1.20695442,  1.47538518, -0.77781422, -0.35861167, -1.31494387,
       -2.10920795]) 
 90.89982676506042
iteration: 17
      fun: nan
 hess_inv: <6x6 LbfgsInvHessProduct with dtype=float64>
      jac: array([  52.07130016,   78.13182492, 2400.56388066, 3915.55172428,
       1014.05535133, 2685.99087576])
  message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
     nfev: 378
      nit: 6
   status: 2
  success: False
        x: array([ 2.02509755,  1.86534638, -0.97105817, -0.64912506, -1.35230929,
       -1.77205649]) 
 111.41410756111145
iteration: 18
      fun: 2947.7195531130933
 hess_inv: <6x6 Lb