In [1]:
from mmnl import MMNL
import numpy as np
import pickle
import pandas as pd


In [ ]:
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

Authorize Google Drive to upload files to the drive

In [ ]:
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

In [2]:
def load_data(path):
    dat = np.load(path)
    X = dat[:, :-1]
    Y = np.reshape(dat[:, -1], (-1, 1))
    return X, Y
X, Y = load_data('data/data.npy')

Load data

In [3]:
%%time
infile = open('./data/1000_Y_dgp_tim.p', 'rb')
Y_dgp = pickle.load(infile)
# Y_dgp = big_dict['theta: [ 1.5  1.  -1.1  0.4  0.1  0.6]']
print(Y_dgp.shape, '\n',Y_dgp)

(2798, 1000) 
 [[3. 3. 0. ... 0. 1. 2.]
 [3. 3. 1. ... 0. 1. 3.]
 [1. 1. 1. ... 0. 3. 1.]
 ...
 [3. 3. 3. ... 3. 3. 3.]
 [3. 3. 3. ... 3. 3. 1.]
 [2. 2. 1. ... 2. 1. 2.]]
Wall time: 31 ms


In [ ]:
%%time
result = []
draws = 250
start = 0
end = 50
method = 'SMC'
for i in range(start,end):
    print('iteration: %i' %(i+1))
    qmc = MMNL(X,Y_dgp[:,i],draws,3,method=method)
    solution = qmc.solver()
    result.append(solution)
    if i%10==9:
        pickle.dump( result, open( "./resultaten/%s(%i)/%i-%i_%s(%i)_timgdp_results.p" %(method,draws,i-9,i,method,draws), "wb" ) )
        result = []
#     f = drive.CreateFile()
#     f.SetContentFile("./resultaten/%i-%i_%s(%i)_results.p" %(i,i+10,method,draws))
#     f.Upload()

iteration: 1
      fun: 2868.6220357723237
 hess_inv: <6x6 LbfgsInvHessProduct with dtype=float64>
      jac: array([ 0.01778062,  0.02128218, -0.0394266 ,  0.00022737,  0.        ,
       -0.05570655])
  message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
     nfev: 406
      nit: 45
   status: 0
  success: True
        x: array([  1.57155517,   1.15185907,  -1.11248825,  -1.44927991,
       -12.1454525 ,  -0.49319082]) 
 24.986066579818726
iteration: 2
      fun: 2820.5514023889514
 hess_inv: <6x6 LbfgsInvHessProduct with dtype=float64>
      jac: array([ 0.01646185,  0.01532499, -0.0091859 ,  0.00031832,  0.        ,
        0.01209628])
  message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
     nfev: 315
      nit: 34
   status: 0
  success: True
        x: array([ 1.48951829,  1.0043434 , -1.1759937 , -8.25941367, -8.98089335,
       -0.61054356]) 
 17.632017374038696
iteration: 3
      fun: 2885.7927001107855
 hess_inv: <6x6 LbfgsInvHessProduct with dtype=float64>